<?php

use Illuminate\Database\Seeder;

class BailConfigurationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $bailConfiguration = [
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 1,
                                    'bc_category' => 'bail_fee',
                                    'bc_type' => 'regular',
                                    'bc_value' => '3',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 1,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'R',
                                    'bc_value' => 'Bail Receipt',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 2,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'C',
                                    'bc_value' => 'County Fee',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 3,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'P',
                                    'bc_value' => 'Payment',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 4,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'X',
                                    'bc_value' => 'Purged Bail',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 5,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'I',
                                    'bc_value' => 'Investment',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 6,
                                    'bc_category' => 'transaction_type',
                                    'bc_type' => 'K',
                                    'bc_value' => 'Backout',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 1,
                                    'bc_category' => 'states',
                                    'bc_type' => 'AL',
                                    'bc_value' => 'Alabama',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 2,
                                    'bc_category' => 'states',
                                    'bc_type' => 'AK',
                                    'bc_value' => 'Alaska',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 3,
                                    'bc_category' => 'states',
                                    'bc_type' => 'AZ',
                                    'bc_value' => 'Arizona',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 4,
                                    'bc_category' => 'states',
                                    'bc_type' => 'AR',
                                    'bc_value' => 'Arkansas',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 5,
                                    'bc_category' => 'states',
                                    'bc_type' => 'CA',
                                    'bc_value' => 'California',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 6,
                                    'bc_category' => 'states',
                                    'bc_type' => 'CO',
                                    'bc_value' => 'Colorado',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 7,
                                    'bc_category' => 'states',
                                    'bc_type' => 'CT',
                                    'bc_value' => 'Connecticut',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 8,
                                    'bc_category' => 'states',
                                    'bc_type' => 'DE',
                                    'bc_value' => 'Delaware',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 9,
                                    'bc_category' => 'states',
                                    'bc_type' => 'FL',
                                    'bc_value' => 'Florida',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 10,
                                    'bc_category' => 'states',
                                    'bc_type' => 'GA',
                                    'bc_value' => 'Georgia',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 11,
                                    'bc_category' => 'states',
                                    'bc_type' => 'HI',
                                    'bc_value' => 'Hawaii',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 12,
                                    'bc_category' => 'states',
                                    'bc_type' => 'ID',
                                    'bc_value' => 'Idaho',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 13,
                                    'bc_category' => 'states',
                                    'bc_type' => 'IL',
                                    'bc_value' => 'Illinois',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 14,
                                    'bc_category' => 'states',
                                    'bc_type' => 'IN',
                                    'bc_value' => 'Indiana',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 15,
                                    'bc_category' => 'states',
                                    'bc_type' => 'IA',
                                    'bc_value' => 'Iowa',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 16,
                                    'bc_category' => 'states',
                                    'bc_type' => 'KS',
                                    'bc_value' => 'Kansas',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 17,
                                    'bc_category' => 'states',
                                    'bc_type' => 'KY',
                                    'bc_value' => 'Kentucky',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 18,
                                    'bc_category' => 'states',
                                    'bc_type' => 'LA',
                                    'bc_value' => 'Louisiana',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 19,
                                    'bc_category' => 'states',
                                    'bc_type' => 'ME',
                                    'bc_value' => 'Maine',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 20,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MD',
                                    'bc_value' => 'Maryland',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 21,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MA',
                                    'bc_value' => 'Massachusetts',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 22,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MI',
                                    'bc_value' => 'Michigan',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 23,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MN',
                                    'bc_value' => 'Minnesota',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 24,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MS',
                                    'bc_value' => 'Mississippi',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 25,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MO',
                                    'bc_value' => 'Missouri',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 26,
                                    'bc_category' => 'states',
                                    'bc_type' => 'MT',
                                    'bc_value' => 'Montana',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 27,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NE',
                                    'bc_value' => 'Nebraska',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 28,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NV',
                                    'bc_value' => 'Nevada',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 29,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NH',
                                    'bc_value' => 'New Hampshire',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 30,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NJ',
                                    'bc_value' => 'New Jersey',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 31,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NM',
                                    'bc_value' => 'New Mexico',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 32,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NY',
                                    'bc_value' => 'New York',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 33,
                                    'bc_category' => 'states',
                                    'bc_type' => 'NC',
                                    'bc_value' => 'North Carolina',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 34,
                                    'bc_category' => 'states',
                                    'bc_type' => 'ND',
                                    'bc_value' => 'North Dakota',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 35,
                                    'bc_category' => 'states',
                                    'bc_type' => 'OH',
                                    'bc_value' => 'Ohio',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 36,
                                    'bc_category' => 'states',
                                    'bc_type' => 'OK',
                                    'bc_value' => 'Oklahoma',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 37,
                                    'bc_category' => 'states',
                                    'bc_type' => 'OR',
                                    'bc_value' => 'Oregon',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 38,
                                    'bc_category' => 'states',
                                    'bc_type' => 'PA',
                                    'bc_value' => 'Pennsylvania',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 39,
                                    'bc_category' => 'states',
                                    'bc_type' => 'RI',
                                    'bc_value' => 'Rhode Island',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 40,
                                    'bc_category' => 'states',
                                    'bc_type' => 'SC',
                                    'bc_value' => 'South Carolina',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 41,
                                    'bc_category' => 'states',
                                    'bc_type' => 'SD',
                                    'bc_value' => 'South Dakota',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 42,
                                    'bc_category' => 'states',
                                    'bc_type' => 'TN',
                                    'bc_value' => 'Tennessee',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 43,
                                    'bc_category' => 'states',
                                    'bc_type' => 'TX',
                                    'bc_value' => 'Texas',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 44,
                                    'bc_category' => 'states',
                                    'bc_type' => 'UT',
                                    'bc_value' => 'Utah',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 45,
                                    'bc_category' => 'states',
                                    'bc_type' => 'VT',
                                    'bc_value' => 'Vermont',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 46,
                                    'bc_category' => 'states',
                                    'bc_type' => 'VA',
                                    'bc_value' => 'Virginia',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 47,
                                    'bc_category' => 'states',
                                    'bc_type' => 'WA',
                                    'bc_value' => 'Washington',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 48,
                                    'bc_category' => 'states',
                                    'bc_type' => 'WV',
                                    'bc_value' => 'West Virginia',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 49,
                                    'bc_category' => 'states',
                                    'bc_type' => 'WI',
                                    'bc_value' => 'Wisconsin',
                                ],
                                [
                                    'bc_create_at' => date('Y-m-d G:i:s'),
                                    'bc_active' => 1,
                                    'bc_order' => 50,
                                    'bc_category' => 'states',
                                    'bc_type' => 'WY',
                                    'bc_value' => 'Wyoming',
                                ],
        ];

        DB::table('bail_configuration')->insert($bailConfiguration);
    }
}
